### ISSUE TITLE
Useless `else` after `if`

### ISSUE THREAD

**Issue by mathieubrd** [leheriss/aws-platform#4]
https://github.com/leheriss/aws-platform/blob/c341beca37c00371bf2ca2de7c6767ef3655a167/app/aws-platform.ts#L33
https://github.com/leheriss/aws-platform/blob/c341beca37c00371bf2ca2de7c6767ef3655a167/app/aws-platform.ts#L45
https://github.com/leheriss/aws-platform/blob/c341beca37c00371bf2ca2de7c6767ef3655a167/app/aws-platform.ts#L71

```typescript
if (!rootOuId || rootOuId == '') {
  throw new Error(
    'No root OU Id in AWS Organizations, cannot deploy Organizations nor Account Factory stacks',
  );
} else {
  // statements
}
```

The `else` is useless here as there is a `throw` in the `if`. You could just write:
```typescript
if (!rootOuId || rootOuId == '') {
  throw new Error(
    'No root OU Id in AWS Organizations, cannot deploy Organizations nor Account Factory stacks',
  );
}

// statements
```

**Comment by leheriss** [comment]
Done
